[package]
name = "rust-caster"
version = "0.10.0"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]

[dependencies]
ansi_term = "0.10.2"
docopt = "0.8.3"
env_logger = "0.5.3"
log = "0.4.1"
rust_cast = "0.10.0"
serde = "1.0.27"
serde_derive = "1.0.27"
